module.exports = {
	"listenport" : 8000,
	"checkReferer" : false,
	"refererRegex" : /^http(s)?:\/\/(www\.)?yourdomain.com.*/i,
	"maxRecentPosts" : 10,
	"postRestrictions" : {
		"titleLength": 50,
		"pasteLength" : 524288
	},
	"supportedExpiryTimes" : [
		{ label: "Never", time: 0 },
		{ label: "5 Minutes", time: 5 },
		{ label: "30 Minutes", time: 30 },
		{ label: "An Hour", time: 60 },
		{ label: "Eight Hours", time: 480 },
		{ label: "A Day", time: 1440 },
		{ label: "Two Weeks", time: 20160 }
	],
	"supportedLanguages" : [
		{ name: 'Shell Script (bash)', alias: 'bash' },
		{ name: 'Erlang', alias: 'erlang' },
		{ name: 'C#', alias: 'cs' },
		{ name: 'Ruby-on-Rails', alias: 'ruby' },
		{ name: 'Diff/Patch', alias: 'diff' },
		{ name: 'JavaScript', alias: 'javascript' },
		{ name: 'LUA', alias: 'lua' },
		{ name: 'XML', alias: 'xml' },
		{ name: 'Markdown', alias: 'markdown' },
		{ name: 'Cascading Style Sheets (CSS)', alias: 'css' },
		{ name: 'LISP', alias: 'lisp' },
		{ name: 'HTTP', alias: 'http' },
		{ name: 'Java', alias: 'java' },
		{ name: 'PHP', alias: 'php' },
		{ name: 'Haskell', alias: 'haskell' },
		{ name: 'Python', alias: 'python' },
		{ name: 'SmallTalk', alias: 'smalltalk' },
		{ name: 'Tex', alias: 'tex' },
		{ name: 'ActionScript', alias: 'actionscript' },
		{ name: 'SQL', alias: 'sql' },
		{ name: 'ini (Configuration File)', alias: 'ini' },
		{ name: 'PERL', alias: 'perl' },
		{ name: 'Scala', alias: 'scala' },
		{ name: 'cmake', alias: 'cmake' },
		{ name: 'Objective C', alias: 'objectivec' },
		{ name: 'VHDL', alias: 'vhdl' },
		{ name: 'CoffeeScript', alias: 'coffeescript' },
		{ name: 'Nginx', alias: 'nginx' },
		{ name: 'R', alias: 'r' },
		{ name: 'JSON', alias: 'json' },
		{ name: 'Django', alias: 'django' },
		{ name: 'Delphi', alias: 'delphi' },
		{ name: 'vbScript', alias: 'vbscript' },
		{ name: 'DOS', alias: 'dos' },
		{ name: 'Apache', alias: 'apache' },
		{ name: 'AppleScript', alias: 'applescript' },
		{ name: 'C++', alias: 'cpp' },
		{ name: 'MatLab', alias: 'matlab' },
		{ name: 'Go', alias: 'go' },
		{ name: 'Plain Text', alias: 'text' }
	]
};